name: Deploy
on:
  push:
    branches:
    - master
jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6]
        
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 24.199.113.17
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd assembackend
          source root/venv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
