name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Create virtual environment
        run: python -m venv /root/venv

      - name: Activate virtual environment
        run: source /root/venv/bin/activate

      - name: Install dependencies and run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dir
          cd assembackend
          python manage.py test

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: 24.199.113.17
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd assembackend
            source /root/venv/bin/activate
            git pull
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo supervisorctl restart all
